### ISSUE TITLE
Cannot find the retrieved 10M dataset

### ISSUE THREAD

**Issue by csuhan** [microsoft/react#3]
Thanks for your great work!
Can you update the link of retrieved 10M subset as the link you provided does not exist.
https://huggingface.co/datasets/react-vl/react-retrieval-datasets/blob/main/imagenet_10m.parquet

**Comment by haotian-liu** [comment]
Thanks for your interest in our work and thank you for the reminder.

This link was accidentally set to private after the release and it is now public.  Please try again.  Thank you!

**Comment by csuhan** [comment]
Thanks for your reply. It works now😀
